language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알림
notifications:
  email:
    recipients:
      - kkddhh2826@gmail.com

# ./gradlew 파일 실행 권한이 없는 경우
before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r springboot-study *
  - mkdir -p deploy
  - mv springboot-study.zip deploy/springboot-study.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hyeonja-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hyeonja-springboot-build
    key: springboot-study.zip
    bundle_type: zip
    application: springboot2-webservice
    deployment_group: springboot-webservice
    region: ap-northeast-2
    wait-until-deployed: true
