language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알림
notifications:
  email:
    recipients:
      - kkddhh2826@gmail.com

# /home/travis/.travis/functions: line 351: ./gradlew: Permission denied
# ./gradlew 파일 실행 권한이 없는 경우
before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r 압축파일이름 *
  - mkdir -p deploy
  - mv 압축파일이름.zip deploy/압축파일이름.zip


deploy:
  - probider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: 버킷명
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true
